/**
  Grants privileges to all users on TABLES, PROCEDURES, FUNCTIONS and SEQUENCES
  so that not only creator can access them.
 */
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO krejct20;
GRANT ALL PRIVILEGES ON ALL PROCEDURES IN SCHEMA public TO krejct20;
GRANT ALL PRIVILEGES ON ALL FUNCTIONS IN SCHEMA public TO krejct20;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO krejct20;

GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO horak108;
GRANT ALL PRIVILEGES ON ALL PROCEDURES IN SCHEMA public TO horak108;
GRANT ALL PRIVILEGES ON ALL FUNCTIONS IN SCHEMA public TO horak108;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO horak108;

GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO formama9;
GRANT ALL PRIVILEGES ON ALL PROCEDURES IN SCHEMA public TO formama9;
GRANT ALL PRIVILEGES ON ALL FUNCTIONS IN SCHEMA public TO formama9;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO formama9;

GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO kocouma4;
GRANT ALL PRIVILEGES ON ALL PROCEDURES IN SCHEMA public TO kocouma4;
GRANT ALL PRIVILEGES ON ALL FUNCTIONS IN SCHEMA public TO kocouma4;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO kocouma4;

GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO sakalond;
GRANT ALL PRIVILEGES ON ALL PROCEDURES IN SCHEMA public TO sakalond;
GRANT ALL PRIVILEGES ON ALL FUNCTIONS IN SCHEMA public TO sakalond;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO sakalond;

GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO cinerpat;
GRANT ALL PRIVILEGES ON ALL PROCEDURES IN SCHEMA public TO cinerpat;
GRANT ALL PRIVILEGES ON ALL FUNCTIONS IN SCHEMA public TO cinerpat;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO cinerpat;

GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO bohmtom1;
GRANT ALL PRIVILEGES ON ALL PROCEDURES IN SCHEMA public TO bohmtom1;
GRANT ALL PRIVILEGES ON ALL FUNCTIONS IN SCHEMA public TO bohmtom1;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO bohmtom1;