/* Drop Tables */

-- Sklad
DROP TABLE IF EXISTS adresa CASCADE;

DROP TABLE IF EXISTS dodavatel CASCADE;

DROP TABLE IF EXISTS kuchar CASCADE;

DROP TABLE IF EXISTS objednavka CASCADE;

DROP TABLE IF EXISTS objednavka_skladnik CASCADE;

DROP TABLE IF EXISTS objednavka_surovina CASCADE;

DROP TABLE IF EXISTS produkt CASCADE;

DROP TABLE IF EXISTS role CASCADE;

DROP TABLE IF EXISTS skladnik CASCADE;

DROP TABLE IF EXISTS skladnik_odvoz CASCADE;

DROP TABLE IF EXISTS surovina CASCADE;

DROP TABLE IF EXISTS surovina_vareni CASCADE;

DROP TABLE IF EXISTS vareni CASCADE;

DROP TABLE IF EXISTS vareni_kuchar CASCADE;

DROP TABLE IF EXISTS vareni_skladnik CASCADE;

DROP TABLE IF EXISTS varka CASCADE;

DROP TABLE IF EXISTS zamestnanec CASCADE;

-- Distribuce
DROP TABLE IF EXISTS dealer CASCADE;

DROP TABLE IF EXISTS odvoz CASCADE;

DROP TABLE IF EXISTS pobocka CASCADE;

DROP TABLE IF EXISTS pobocka_restaurace CASCADE;

DROP TABLE IF EXISTS prodej CASCADE;

DROP TABLE IF EXISTS restaurace_odvoz CASCADE;

DROP TABLE IF EXISTS restauraceprodukty CASCADE;

DROP TABLE IF EXISTS ridic CASCADE;

DROP TABLE IF EXISTS pristupovaprava CASCADE;

DROP TABLE IF EXISTS role_pristupovaprava CASCADE;

DROP TABLE IF EXISTS produkt_odvoz CASCADE;